from __future__ import annotations

# Production engine semantic payload surface. Every engine command is fail-closed:
# fields not listed here are rejected before authority checks/reducers. This
# prevents ignored caller data from becoming a shadow control channel as reducers
# evolve.
#
# scene_consequence is an internal attempt/event transport used by stable operations.
# Player-facing operations do not advertise or permit raw scene_consequence writes.
# The surface-only interaction_action contract lives
# in api/interaction_surface.py and is translated before it reaches the engine.
COMMAND_PAYLOAD_KEYS: dict[str, frozenset[str]] = {
    "fortification_logistics": frozenset({"action", "site_ref", "source_depot_ref", "destination_depot_ref", "cargo", "convoy_ref"}),
    "settlement_civic_action": frozenset({"action", "location_ref", "case_ref", "case_kind", "severity", "subject_ref", "evidence_refs", "disposition", "court_case_ref", "outbreak_ref", "syndrome", "transmission_route", "known_cases", "exposed_population", "exposure_pressure", "population_resistance", "severity_band", "incubation_hours", "infectious_hours", "active", "quarantine_strength", "supply_days"}),
    "strategic_crossing_action": frozenset({"route_ref", "action", "water_stage", "amount", "quantity"}),
    "organization_action": frozenset({"action", "organization_ref", "name", "organization_class", "location_ref", "amount_silver", "capacity", "person_ref", "role", "force_ref", "policy_key", "policy_value"}),
    "advance_time": frozenset({"hours", "target_time", "stop_on_player_event", "activity_policy"}),
    "battle_resolve": frozenset({"attacker_formation_refs", "defender_formation_refs", "operation_ref", "controlled_side", "objective", "battlefield_ref", "sector_ref"}),
    "battlefield_control": frozenset({"action", "operation_ref", "battlefield_ref", "name", "side_refs", "layout_ref", "formation_ref", "side_ref", "sector_ref", "target_sector_ref", "pace", "order", "termination_kind", "winner_side_ref", "accepted_side_refs", "evidence_ref"}),
    "career_event": frozenset({"person_ref", "kind", "merit", "qualification_ref", "grade", "office", "affiliation_ref", "evidence_ref", "grantor_ref"}),
    "military_allegiance_action": frozenset({"action", "formation_refs", "proposed_commander_ref", "claimant_ref", "basis_ref"}),
    "command_group_action": frozenset({"action", "command_group_ref", "display_name", "commander_ref", "parent_ref", "person_ref", "formation_ref", "subordinate_group_ref", "unit_slot", "role", "successor_refs", "order", "issuer_ref", "communication_ref", "doctrine_ref", "location_ref", "authorized_strength", "authorized_direct_unit_slots", "mission", "allow_auto_staff", "operation_ref"}),
    "command_group_train": frozenset({"command_group_ref", "hours", "focus"}),
    "commission_action": frozenset({"action", "request_ref", "commission_ref", "category", "issuer_ref", "report_ref", "evidence_refs"}),
    "commitment_action": frozenset({"action", "commitment_ref", "obligor_ref", "beneficiary_ref", "kind", "due_at", "description", "evidence_ref"}),
    "cohort_training": frozenset({"hours", "cohort_ref"}),
    "command_assign": frozenset({"formation_ref", "commander_ref", "command_authority"}),
    "command_transfer": frozenset({"formation_ref", "commander_ref", "command_authority"}),
    "economy_transfer": frozenset({"state", "direction", "amount_silver"}),
    "enlisted_service_pay": frozenset({"state", "amount_silver"}),
    "equipment_consume": frozenset({"item_key", "quantity"}),
    "equipment_drop": frozenset({"item_key", "quantity"}),
    "equipment_equip": frozenset({"item_key", "quantity"}),
    "equipment_issue": frozenset({"item_key", "quantity", "target_ref"}),
    "equipment_loot": frozenset({"item_key", "quantity"}),
    "equipment_return": frozenset({"item_key", "quantity", "target_ref"}),
    "equipment_transfer": frozenset({"item_key", "quantity", "target_ref"}),
    "equipment_unequip": frozenset({"item_key", "quantity"}),
    "family_event": frozenset({"house_ref", "kind", "person_ref", "partner_ref", "proposal_ref", "mother_ref", "father_ref", "child_ref", "name", "succession_ref"}),
    "force_assignment": frozenset({"formation_ref", "commander_ref", "command_authority"}),
    "formation_assign": frozenset({"formation_ref", "commander_ref", "command_authority"}),
    "formation_create": frozenset({"state", "force_ref", "formation_ref", "role", "composition", "personnel", "authorized_strength", "formation_class", "equipment_units", "equipment_units_by_role", "location_ref", "commander_ref", "name", "command_authority", "doctrine_ref", "training_ref"}),
    "formation_demobilize": frozenset({"formation_ref"}),
    "formation_dissolve": frozenset({"formation_ref"}),
    "formation_doctrine_set": frozenset({"formation_ref", "formation_refs", "doctrine_ref", "doctrine_behavior"}),
    "formation_equipment_repair": frozenset({"formation_ref", "hours", "categories"}),
    "formation_merge": frozenset({"formation_refs"}),
    "formation_mobilize": frozenset({"formation_ref", "formation_refs"}),
    "formation_move": frozenset({"formation_ref", "destination_ref"}),
    "formation_reconstitute": frozenset({"formation_ref", "target_personnel", "equipment_units", "equipment_units_by_role", "replacement_composition"}),
    "formation_split": frozenset({"formation_ref", "new_formation_ref", "personnel", "name"}),
    "formation_train": frozenset({"formation_ref", "formation_refs", "hours", "participant_refs"}),
    "formation_training_set": frozenset({"formation_ref", "formation_refs", "training_ref"}),
    "fortification_materialize": frozenset({"fortification_ref", "location_ref", "garrison_formation_refs", "state", "commander_ref", "integrity"}),
    "health_injury": frozenset({"injury", "severity"}),
    "health_recovery": frozenset({"hours"}),
    "medical_treatment": frozenset({"target_ref", "treatment", "practitioner_ref", "facility_ref", "body_site", "hours"}),
    "house_action": frozenset({"house_ref", "action", "subject_ref", "duty", "policy_key", "policy_value", "target_grade", "grantor_ref", "evidence_ref", "location_ref", "operation_ref", "polity_name", "corps_key", "source_state", "source_site_ref", "applicant_count"}),
    "individual_training": frozenset({"focus", "hours"}),
    "information_create": frozenset({"information_ref", "claim", "knowers", "confidence", "provenance", "subject_ref", "epistemic_kind", "confidence_milli", "evidence_refs", "classification", "location_ref", "discoverability_milli"}),
    "information_deliver": frozenset({"information_ref", "target_ref", "source_ref", "channel"}),
    "investigation_action": frozenset({"action", "investigation_ref", "question", "subject_ref", "location_ref", "investigator_ref", "hours"}),
    "institution_project": frozenset({"institution_ref", "project_ref", "duration_hours", "kind", "magnitude", "effect"}),
    "market_purchase": frozenset({"item_key", "quantity"}),
    "market_sell": frozenset({"item_key", "quantity"}),
    "mercenary_contract": frozenset({"mercenary_ref", "action", "contract_ref", "amount_silver", "term_days", "location_ref", "reason"}),
    "operation_create": frozenset({"operation_ref", "objective", "formation_refs", "location_ref"}),
    "operation_transition": frozenset({"operation_ref", "status"}),
    "person_materialize": frozenset({"state", "person_ref", "role", "name", "birth_date", "personal_force_ref", "source_stratum", "source_location_ref", "selection_profile", "source_cohort_ref", "representation", "formation_ref"}),
    "personal_combat": frozenset({"opponent_ref", "opponent_refs", "ally_refs", "target_ref", "participant_positions", "local_obstacles", "objective", "objective_position", "objective_radius_m", "objective_hold_seconds", "escape_distance_m", "duration_minutes", "distance_m", "intent_sequence", "stop_on_decision"}),
    "recover_projectiles": frozenset({"minutes", "projectile_item_id"}),
    "population_transfer": frozenset({"state", "personnel", "source_stratum", "destination_stratum"}),
    "project_resolve": frozenset({"institution_ref", "project_ref"}),
    "project_cancel": frozenset({"institution_ref", "project_ref"}),
    "recruitment": frozenset({"state", "personnel", "source_stratum", "background_profile", "selection_profile", "selection_retain_fraction", "role"}),
    "recruitment_campaign_start": frozenset({"state", "campaign_ref", "applicant_count", "destination_force_ref", "role", "location_ref"}),
    "recruitment_campaign_stage": frozenset({"campaign_ref", "selection_profile", "retain_count", "retain_fraction"}),
    "recruitment_campaign_train": frozenset({"campaign_ref", "hours"}),
    "recruitment_campaign_finalize": frozenset({"campaign_ref"}),
    "recruitment_campaign_cancel": frozenset({"campaign_ref"}),
    "relationship_change": frozenset({"source_ref", "target_ref", "kind", "delta", "basis_ref"}),
    "reputation_event": frozenset({"subject_ref", "audience_ref", "delta", "event_type", "dimension", "source_event_ref", "basis", "witnesses"}),
    "resupply": frozenset({"formation_ref", "war_arrows", "war_bolts", "remount_horses", "construction_material_units"}),
    "scene_consequence": frozenset({"summary"}),
    "siege_action": frozenset({"siege_ref", "action", "days", "hours", "target", "method", "blueprint_ref", "quantity", "source_formation_ref", "work_ref", "cycles", "route_refs", "attacker_formation_refs", "defender_formation_refs", "terms"}),
    "siege_start": frozenset({"siege_ref", "fortification_ref", "attacker_formation_refs"}),
    "state_action": frozenset({"state", "action", "goal", "person_ref", "office", "capabilities", "source_state", "severity", "provenance", "information_ref", "polity_ref"}),
    "state_levy_call": frozenset({"state", "levy_ref", "personnel", "location_ref", "role"}),
    "state_levy_demobilize": frozenset({"state", "levy_ref"}),
    "polity_action": frozenset({"polity_ref", "action", "goal", "location_ref", "policy_key", "policy_value", "person_ref", "target_ref", "war_goal", "treaty_kind", "direction", "duration_days", "amount_silver", "treaty_ref", "proposal_ref", "hostage_person_ref", "counter_hostage_person_ref", "marriage_person_ref", "marriage_partner_ref", "offer_location_refs", "request_location_refs", "coalition_target_ref", "invitee_refs", "investment_silver", "case_ref", "case_kind", "subject_ref", "evidence_refs", "claimant_ref", "victim_refs", "applicable_law_ref", "office_key", "decree_text", "market_name", "remedy_kind", "custodian_formation_ref", "prisoner_group_ref", "recipient_ref", "legal_basis_ref"}),
    "territorial_consequence": frozenset({"location_ref", "controller", "siege_ref", "operation_ref"}),
    "travel": frozenset({"destination_ref", "mode", "formation_refs"}),
    "custody_action": frozenset({"action","source_formation_ref","custodian_formation_ref","personnel","terms","prisoner_group_ref","guards","depot_ref","food_kg","water_person_days","destination_ref","amount_silver","other_prisoner_group_ref","topic_ref","statement","destination_force_ref","person_ref","legal_basis_ref"}),
}

HOSTILE_DIMENSIONS = (
    "negative_or_zero",
    "absurd_magnitude",
    "nonexistent_reference",
    "wrong_location",
    "wrong_state_or_owner",
)
